# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/vg0-root";
    fsType = "ext4";

    options = [
      # Root filesystem je na LVM uvnitř LUKS.
      #
      # Při vzdáleném odemykání může initrd čekat
      # delší dobu na dostupnost sítě, VPN nebo VPS.
      #
      # Bez této volby systemd čeká na zařízení
      # /dev/mapper/vg0-root pouze omezenou dobu.
      #
      # Hodnota 0 znamená čekání bez časového limitu.
      "x-systemd.device-timeout=0"
    ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/931a30f8-fc4d-455f-bf71-caa890b1ab38";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/74A2-1B2C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/vg0-home";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/mapper/vg0-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
