# Do not modify this file! It was generated by nixos-generate-config.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [
    "dm-snapshot"
  ];

  boot.kernelModules = [
    "kvm-amd"
  ];

  boot.extraModulePackages = [ ];

  # =========================
  # LUKS – SYSTEM DISK
  # =========================

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/5a775301-f99e-4b41-9332-dbbfc8947db6";

  # =========================
  # BTRFS – ROOT
  # =========================

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";

    options = [
      "subvol=@root"
      "compress=zstd"
      "noatime"

      # Při vzdáleném odemykání může initrd čekat
      # libovolně dlouho na dostupnost VPN a VPS.
      #
      # Bez této volby může systemd ukončit čekání
      # na /dev/mapper/cryptroot po device timeoutu.
      #
      # Hodnota 0 znamená čekání bez časového limitu.
      "x-systemd.device-timeout=0"
    ];
  };

  # =========================
  # BTRFS – NIX STORE
  # =========================

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";

    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  # =========================
  # BTRFS – SYSTEM LOGS
  # =========================

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";

    options = [
      "subvol=@log"
      "compress=zstd"
      "noatime"
    ];
  };

  # =========================
  # EFI SYSTEM PARTITION
  # =========================

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0096-72B3";
    fsType = "vfat";

    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # Server nemá swap partition.
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}